services:
  - type: web
    name: expense-tracker-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: mongodb+srv://sandeepkumardwibei09_db_user:kyp2CIFUI6BzdeV1@cluster0.gghufet.mongodb.net/?appName=Cluster0
        sync: false
      - key: mysecret1234
        sync: false
